// x402 facilitator (JPYC) のカタログ面: /api/discovery と first-party の demo / stores。
// 掲載は enableX402Facilitator に連動する (lib/openapi/document.ts の buildOpenApiDocument)。

import { USDC_STORES_BAZAAR } from '@/lib/x402/usdcStores';
import { firstPartyPrice, paymentInfo } from '@/lib/openapi/payment';
import { PAID_RESPONSES, schemaFromExample } from '@/lib/openapi/schema';

export const DISCOVERY_OPENAPI_PATHS = {
  '/api/discovery/{id}': {
    get: {
      tags: ['x402 Catalog'],
      summary: 'Get one public seller listing by exact ID',
      description: 'Independent of catalog pagination. Hidden, inactive and reserved-origin listings are excluded. Seller gates must pin the ID and recipient from their own configuration.',
      security: [],
      parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', minLength: 1, maxLength: 100 } }],
      responses: {
        '200': {
          description: 'Single public listing in the discovery item shape',
          content: { 'application/json': { schema: { $ref: '#/components/schemas/DiscoveryItem' } } },
        },
        '400': { description: 'Invalid resource ID.' },
        '404': { description: 'The facilitator is disabled or the listing is not public.' },
        '429': { description: 'Too many requests from this IP address.' },
        '503': { description: 'The resource storage is temporarily unavailable.' },
      },
    },
  },
  '/api/discovery': {
    get: {
      tags: ['x402 Catalog'],
      summary: 'List payable x402 resources for agent comparison',
      responses: {
        '200': {
          description: 'First-party and registered resources with payable requirements',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/DiscoveryEnvelope' },
            },
          },
        },
        '404': { description: 'The x402 facilitator is disabled.' },
        '503': { description: 'The resource catalog is temporarily unavailable.' },
      },
    },
  },
  '/api/paid/demo': {
    get: {
      tags: ['x402 Catalog'],
      summary: 'Unlock a signed hello (x402 end-to-end demo)',
      description:
        'Smallest payable resource. Use it to confirm the 402 challenge, JPYC payment and unlock work end to end before wiring a real paid API.',
      'x-payment-info': paymentInfo(firstPartyPrice('/api/paid/demo')),
      'x-payment-protocol': 'x402',
      'x-payment-asset': 'JPYC',
      responses: {
        '200': {
          description: 'Unlock greeting after settlement',
          content: {
            'application/json': {
              example: {
                message: 'Payment verified — welcome to the x402 + JPYC rail.',
                paidAt: '2026-07-28T00:00:00.000Z',
              },
            },
          },
        },
        ...PAID_RESPONSES,
      },
    },
  },
  '/api/paid/stores': {
    get: {
      tags: ['x402 Catalog'],
      summary: 'Unlock the curated JPYC acceptance directory',
      description:
        'Curated JSON of exchanges, dApps and bridges that accept JPYC, with attribution.',
      'x-payment-info': paymentInfo(firstPartyPrice('/api/paid/stores')),
      'x-payment-protocol': 'x402',
      'x-payment-asset': 'JPYC',
      responses: {
        '200': {
          description: 'Curated store list after settlement',
          content: {
            'application/json': {
              schema: schemaFromExample(USDC_STORES_BAZAAR.output.example),
              example: USDC_STORES_BAZAAR.output.example,
            },
          },
        },
        ...PAID_RESPONSES,
      },
    },
  },
} as const;

export const DISCOVERY_OPENAPI_SCHEMAS = {
  DiscoveryItem: {
    type: 'object',
    required: [
      'resource',
      'description',
      'category',
      'priceJpyc',
      'network',
      'accepts',
      'verifiedAt',
    ],
    properties: {
      id: { type: 'string', description: 'Registry listing ID; present for registered seller resources.' },
      resource: { type: 'string', format: 'uri' },
      title: { type: 'string', description: 'Short display name (first-party, or seller-provided)' },
      trigger: { type: 'string', description: 'When to use this resource' },
      description: { type: 'string' },
      category: { type: 'string' },
      priceJpyc: { type: 'string', pattern: '^[1-9][0-9]*$' },
      docsUrl: { type: 'string', format: 'uri', pattern: '^https://', maxLength: 512 },
      license: { type: 'string', maxLength: 60 },
      updatedAt: { type: 'string', format: 'date-time' },
      official: {
        type: 'boolean',
        const: true,
        description: 'Present only for first-party resources generated by OpenPay.',
      },
      network: { type: 'string', description: 'CAIP-2 network identifier' },
      accepts: {
        type: 'array',
        description: 'Payable x402 requirements including the OpenPay fee extension.',
        items: { type: 'object' },
      },
      verifiedAt: {
        type: ['string', 'null'],
        format: 'date-time',
        description: 'Last successful OpenPay gate verification, or null when not yet verified.',
      },
    },
  },
  DiscoveryEnvelope: {
    type: 'object',
    required: ['x402Version', 'items'],
    properties: {
      x402Version: { type: 'integer', const: 1 },
      items: {
        type: 'array',
        items: { $ref: '#/components/schemas/DiscoveryItem' },
      },
    },
  },
} as const;
