import assert from 'node:assert/strict';
import { test } from 'node:test';
import { webcrypto } from 'node:crypto';
import { DeliveryError, verifyDeliveryTicket as verify, deliveryKeyThumbprint, ticketFromRequest, createDeliveryGate } from '../src/delivery.mjs';
import { fixture, base, signer, signingKey, alternate, encode, signedRaw, ticket, remote, response } from './delivery.fixture.mjs';

const rejects = (input, code = 'invalid_ticket') => assert.rejects(verify(input), (error) => {
  assert.ok(error instanceof DeliveryError);
  assert.equal(error.code, code); assert.equal(error.message, code); assert.equal(error.cause, undefined);
  return true;
});

test('pins the shared 570-byte fixture, public thumbprint and independent RFC 8032 signature', async () => {
  assert.equal(ticket(), fixture.ticket);
  assert.equal(Buffer.byteLength(fixture.ticket), fixture.measurements.ticketBytes);
  assert.equal(await deliveryKeyThumbprint(fixture.publicJwk.x), fixture.publicJwk.kid);
  assert.deepEqual(await verify(base), { address: fixture.claims.sub, product: fixture.claims.product,
    revision: 3, basis: 'purchase', exp: 1700000060, iat: 1700000000, jti: fixture.claims.jti, kid: fixture.publicJwk.kid });
  assert.deepEqual(signer.jwk, fixture.publicJwk);
  assert.equal(Buffer.from(fixture.publicJwk.x, 'base64url').toString('hex'), 'd75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a');
  // This independent published signature is not generated by the test signer.
  const sig = Buffer.from('e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b', 'hex');
  const key = await webcrypto.subtle.importKey('jwk', fixture.publicJwk, 'Ed25519', false, ['verify']);
  assert.equal(await webcrypto.subtle.verify('Ed25519', key, sig, new Uint8Array()), true);
  await createDeliveryGate(base).ready();
});
for (const vector of fixture.negative) {
  test(`shared negative: ${vector.name}`, async () => {
    await rejects({ ...base, ticket: vector.ticket, now: () => vector.now * 1000 },
      { wrong_alg: 'unsupported_algorithm', tampered_payload: 'invalid_ticket', expired: 'ticket_expired' }[vector.name]);
  });
}

test('rejects segment count, malformed/noncanonical unpadded base64url, invalid UTF-8 and byte limits', async () => {
  const [h, p, s] = fixture.ticket.split('.');
  for (const bad of [null, 1, '', h + '.' + p, fixture.ticket + '.extra', `.${p}.${s}`,
    `${h}=.${p}.${s}`, `${h}.${p}=.${s}`, fixture.ticket + '=',
    `${h}.${p}.${s.slice(0, -1)}h`, // same decoded bytes as g, nonzero pad bits
    `${h}.${p}.${s.slice(1)}`, `${h}.${p}.${'A'.repeat(86)}`, `${h}.${p}.${'A'.repeat(87)}`,
    `${'A'.repeat(1025)}.${p}.${s}`, `${h}.${'A'.repeat(4097)}.${s}`,
    `${h}.${p}.***`, `${h}.${p}.AA+_`, `${h}.${p}.A`, `${h}.${p}. AA`,
    `${h}.${Buffer.from([0xff]).toString('base64url')}.${s}`, `${Buffer.from([0xc0, 0xaf]).toString('base64url')}.${p}.${s}`,
    `${h}.${encode({ ...fixture.claims, rev: 4 })}.${s}`]) await rejects({ ...base, ticket: bad });
  // The exact encoded header/payload ceilings are accepted, with original whitespace signed.
  const hRaw = JSON.stringify(fixture.header).padEnd(768);
  const pRaw = JSON.stringify(fixture.claims).padEnd(3072);
  assert.equal(encode(hRaw).length, 1024); assert.equal(encode(pRaw).length, 4096);
  assert.equal((await verify({ ...base, ticket: signedRaw(hRaw, pRaw) })).revision, 3);
});

test('requires exact header set; rejects jku/x5u/jwk/crit/b64 rather than ignoring extensions', async () => {
  for (const name of Object.keys(fixture.header)) await rejects({ ...base, ticket: ticket({ [name]: undefined }) });
  for (const alg of ['none', 'HS256', 'Ed448', 'eddsa', null, 1]) await rejects({ ...base, ticket: ticket({ alg }) }, 'unsupported_algorithm');
  for (const patch of [{ typ: 'JWT' }, { typ: null }, { kid: '' }, { kid: 'A'.repeat(42) }, { kid: 'A'.repeat(44) },
    { kid: fixture.publicJwk.kid.slice(0, -1) + 'l' }, { jku: 'https://attacker.example' }, { x5u: 'https://attacker.example' },
    { jwk: fixture.publicJwk }, { crit: [] }, { crit: 'exp' }, { b64: false }, { b64: true }, { extra: true }]) {
    await rejects({ ...base, ticket: ticket(patch) });
  }
  await rejects({ ...base, ticket: ticket({ kid: 'A'.repeat(43) }) }, 'unknown_key');
});

test('rejects flat JSON shape, invalid grammar and duplicate or escaped member names', async () => {
  const header = JSON.stringify(fixture.header); const claims = JSON.stringify(fixture.claims);
  for (const raw of ['[]', 'null', 'false', '1', '"text"', '{}', '{bad}', '{"x":}', header + '{}',
    header.replace('{', '{"alg":"EdDSA",'), header.replace('{', '{"\\u006bid":"bad",')]) {
    await rejects({ ...base, ticket: signedRaw(raw, claims) });
  }
  for (const raw of ['[]', 'null', '1', '{}', '{', claims.replace('{', '{"rev":3,'), claims.replace('{', '{"\\u0072ev":3,'),
    claims.replace('"rev":3', '"rev":{"nested":3}'), claims.replace('"aud":"https://files.example"', '"aud":["https://files.example"]')]) {
    await rejects({ ...base, ticket: signedRaw(header, raw) });
  }
  const escaped = claims.replace('"rev"', '"\\u0072ev"');
  assert.equal((await verify({ ...base, ticket: signedRaw(header, escaped) })).revision, 3);
});

test('requires every claim and validates version, revision, basis, wallet, jti and exact 60s integer lifetime', async () => {
  for (const name of Object.keys(fixture.claims)) await rejects({ ...base, ticket: ticket({}, { [name]: undefined }) });
  for (const patch of [{ v: 2 }, { v: '1' }, { sub: '0x123' }, { sub: '0x' + 'g'.repeat(40) }, { sub: 123 },
    { rev: 0 }, { rev: -1 }, { rev: 1.5 }, { rev: Number.MAX_SAFE_INTEGER + 1 }, { rev: '3' }, { basis: 'owner' },
    { jti: 'A'.repeat(32) }, { jti: 'ab' }, { jti: 1 }, { iat: '1700000000' }, { exp: '1700000060' },
    { iat: 1700000000.5 }, { exp: 1700000061 }, { exp: null }, { iat: Infinity },
    { iat: Number.MAX_SAFE_INTEGER + 1, exp: Number.MAX_SAFE_INTEGER + 61 }, { extra: true }]) {
    await rejects({ ...base, ticket: ticket({}, patch) });
  }
  assert.equal((await verify({ ...base, ticket: ticket({}, { basis: 'holder' }) })).basis, 'holder');
  // Deliberate SDK boundary: server enforces EIP-55, SDK preserves signed hex spelling.
  const address = fixture.claims.sub.toLowerCase();
  assert.equal((await verify({ ...base, ticket: ticket({}, { sub: address }) })).address, address);
});

test('normalizes configured issuer/audience; never normalizes attacker claims or takes key URLs from tickets', async () => {
  await verify({ ...base, audience: 'https://FILES.example:443/', issuer: 'https://OPEN-PAY.JP:443/' });
  await verify({ ...base, audience: 'https://files.example/path?q=1', issuer: 'https://open-pay.jp/path' });
  for (const [patch, code] of [
    [{ iss: 'https://other.example' }, 'wrong_issuer'], [{ iss: 'https://OPEN-PAY.JP:443/' }, 'wrong_issuer'],
    [{ aud: 'https://other.example' }, 'wrong_audience'], [{ aud: 'https://FILES.example:443/' }, 'wrong_audience'],
    [{ product: 'h_' + 'b'.repeat(32) }, 'wrong_product'], [{ product: 'h_' + 'A'.repeat(32) }, 'wrong_product'],
    [{ product: null }, 'wrong_product'],
  ]) await rejects({ ...base, ticket: ticket({}, patch) }, code);
  for (const [patch, code] of [[{ audience: 'https://files.example:444' }, 'wrong_audience'],
    [{ audience: 'invalid' }, 'wrong_audience'], [{ issuer: 'http://open-pay.jp' }, 'wrong_issuer'],
    [{ product: '../file' }, 'wrong_product'], [{ origin: 'http://localhost' }, 'keys_unavailable'],
    [{ origin: 'https://user:pass@keys.example' }, 'keys_unavailable']]) await rejects({ ...base, ...patch }, code);
});

test('expiry equality denies; iat+30 allows, iat+31 denies; skew never extends expiry', async () => {
  await rejects({ ...base, now: () => 1700000060000 }, 'ticket_expired');
  await verify({ ...base, now: () => 1700000059999 });
  await verify({ ...base, now: () => 1699999970000 });
  await rejects({ ...base, now: () => 1699999969000 }, 'ticket_not_yet_valid');
  await verify({ ...base, now: () => 1699999969000, maxSkewSeconds: 31 });
  await rejects({ ...base, now: () => 1699999999999, maxSkewSeconds: 0 }, 'ticket_not_yet_valid');
  await rejects({ ...base, now: () => 1700000060000, maxSkewSeconds: 1000 }, 'ticket_expired');
  for (const maxSkewSeconds of [-1, NaN, Infinity, '30']) await rejects({ ...base, maxSkewSeconds });
  await rejects({ ...base, now: () => NaN });
  // The signature is checked before expiry, even when the ticket has expired.
  await rejects({ ...base, ticket: fixture.negative[1].ticket, now: () => 1700000060000 });
});

test('expiry is checked after slow key fetch, after signature verification, and after replay consume', async (t) => {
  let now = 1700000030000; let consumes = 0;
  const replayStore = { async consume() { consumes++; return true; } };
  await rejects(remote({ now: () => now, replayStore, fetch: async () => { await Promise.resolve(); now = 1700000060000; return response(); } }), 'ticket_expired');
  assert.equal(consumes, 0);
  now = 1700000030000;
  const original = globalThis.crypto.subtle.verify.bind(globalThis.crypto.subtle);
  const mock = t.mock.method(globalThis.crypto.subtle, 'verify', async (...args) => { const valid = await original(...args); now = 1700000060000; return valid; });
  await rejects({ ...base, now: () => now, replayStore }, 'ticket_expired');
  mock.mock.restore(); assert.equal(consumes, 0);
  now = 1700000030000;
  await rejects({ ...base, now: () => now, replayStore: { async consume() { now = 1700000060000; return true; } } }, 'ticket_expired');
});

test('rejects entire invalid key sets, including private keys, bad thumbprints, wrong metadata and duplicates', async () => {
  for (const keys of [null, {}, [], [null], [[]], [fixture.publicJwk, {}], [fixture.publicJwk, fixture.publicJwk], Array(9).fill(fixture.publicJwk)]) {
    await rejects({ ...base, keys }, 'keys_unavailable');
  }
  const patches = [{ kty: 'RSA' }, { crv: 'Ed448' }, { x: 'AA' }, { x: fixture.publicJwk.x + '=' },
    { x: fixture.publicJwk.x.slice(0, -1) + 'p' }, { kid: alternate.jwk.kid }, { kid: 'unknown' },
    { d: fixture.seed.slice(2) }, { alg: 'HS256' }, { use: 'enc' }, { key_ops: ['verify'] },
    ...Object.keys(fixture.publicJwk).map((field) => ({ [field]: undefined }))];
  for (const patch of patches) await rejects({ ...base, keys: [{ ...fixture.publicJwk, ...patch }] }, 'keys_unavailable');
  // No arbitrary kid guessing: even a valid alternate key cannot verify this ticket.
  await rejects({ ...base, keys: [alternate.jwk] }, 'unknown_key');
  await verify({ ...base, keys: [alternate.jwk, fixture.publicJwk] });
  const eight = [fixture.publicJwk, ...Array.from({ length: 7 }, (_, i) => signingKey('0x' + String(i).repeat(64)).jwk)];
  await verify({ ...base, keys: eight });
  await verify(remote({ fetch: async () => response(eight) }));
});

test('explicit keys never fetch, including readiness, unknown keys, empty and invalid sets', async () => {
  let calls = 0; const fetch = async () => { calls++; throw new Error('must not fetch'); };
  await verify({ ...base, fetch }); await createDeliveryGate({ ...base, fetch }).ready();
  await rejects({ ...base, fetch, ticket: ticket({}, {}, alternate) }, 'unknown_key');
  await rejects({ ...base, fetch, keys: [] }, 'keys_unavailable');
  await rejects({ ...base, fetch, keys: null }, 'keys_unavailable');
  assert.equal(calls, 0);
});

test('JWKS HTTPS fetch uses manual redirect and bounded protocol; rejects HTTP, redirect and origin substitution', async () => {
  const input = remote(); let calls = 0;
  input.fetch = async (url, init) => {
    calls++; assert.equal(url, `${input.origin}/.well-known/openpay-delivery-keys.json`);
    assert.equal(init.redirect, 'manual'); assert.equal(init.method, 'GET');
    assert.equal(init.headers.accept, 'application/json'); assert.ok(init.signal instanceof AbortSignal);
    return response();
  };
  await verify(input); await verify(input); assert.equal(calls, 1);
  for (const status of [201, 204, 301, 302, 303, 307, 308, 404, 500]) {
    await rejects(remote({ fetch: async () => new Response(null, { status }) }), 'keys_unavailable');
  }
  for (const patch of [{ redirected: true }, { type: 'opaqueredirect' }, { url: 'https://evil.example/keys' }]) {
    await rejects(remote({ fetch: async () => Object.assign({ status: 200, headers: new Headers(), body: response().body }, patch) }), 'keys_unavailable');
  }
  await rejects(remote({ fetch: async () => { throw new Error('SECRET_URL_BODY'); } }), 'keys_unavailable');
});

test('JWKS bounds content length, streamed size, JSON/UTF-8, member sets, Age and key count', async () => {
  for (const make of [
    () => new Response('bad json'), () => Response.json(null), () => Response.json([]), () => Response.json({ keys: [] }),
    () => Response.json({ keys: [fixture.publicJwk], extra: true }), () => response(Array(9).fill(fixture.publicJwk)),
    () => response([{ ...fixture.publicJwk, kid: alternate.jwk.kid }]), () => response([fixture.publicJwk, fixture.publicJwk]),
    () => new Response('{"keys":[],"keys":' + JSON.stringify([fixture.publicJwk]) + '}'),
    () => new Response(JSON.stringify({ keys: [fixture.publicJwk] }).replace('"kid":', '"kid":"bad","\\u006bid":')),
    () => new Response(new Uint8Array([0xff])), () => response(undefined, { 'content-length': '16385' }),
    () => response(undefined, { 'content-length': '-1' }), () => new Response(' '.repeat(16385)),
    () => response(undefined, { age: '300' }), () => response(undefined, { age: '301' }),
    () => response(undefined, { age: '-1' }), () => response(undefined, { age: 'NaN' }),
    () => response(undefined, { age: '0.1' }), () => response(undefined, { age: '9007199254740992' }),
  ]) await rejects(remote({ fetch: async () => make() }), 'keys_unavailable');
  let cancelled = false;
  await rejects(remote({ fetch: async () => new Response(new ReadableStream({
    pull(controller) { controller.enqueue(new Uint8Array(8193)); }, cancel() { cancelled = true; },
  })) }), 'keys_unavailable');
  assert.equal(cancelled, true);
  const padded = JSON.stringify({ keys: [fixture.publicJwk] }).padEnd(16384);
  await verify(remote({ fetch: async () => new Response(padded) }));
});

test('8s deadline aborts both a stalled fetch and a stalled body, without relying on custom fetch to honor abort', async () => {
  const signals = [];
  const stalledFetch = remote({ fetch: async (_, init) => { signals.push(init.signal); return new Promise(() => {}); } });
  const stalledBody = remote({ fetch: async (_, init) => {
    signals.push(init.signal); return new Response(new ReadableStream({ start() {} }));
  } });
  const start = Date.now();
  await Promise.all([rejects(stalledFetch, 'keys_unavailable'), rejects(stalledBody, 'keys_unavailable')]);
  assert.ok(Date.now() - start >= 7900); assert.equal(signals.every((signal) => signal.aborted), true);
});

test('cache subtracts upstream Age and fetch elapsed time; stale keys are never used after failure', async () => {
  let now = 1700000030000; let calls = 0;
  const input = remote({ now: () => now, fetch: async () => { calls++; return response(undefined, { age: '299' }); } });
  await verify(input); now += 999; await verify(input); assert.equal(calls, 1);
  now += 1; await verify(input); assert.equal(calls, 2);
  // Retrieval time also counts against remaining freshness.
  await rejects(remote({ now: () => now, fetch: async () => { now += 1000; return response(undefined, { age: '299' }); } }), 'keys_unavailable');
  let fail = false;
  const stale = remote({ now: () => now, fetch: async () => { if (fail) throw new Error('offline'); return response(); } });
  await verify(stale); now += 299999;
  const currentTicket = () => ticket({}, { iat: Math.floor(now / 1000), exp: Math.floor(now / 1000) + 60 });
  fail = true; await verify({ ...stale, ticket: currentTicket() });
  now += 1;
  await rejects({ ...stale, ticket: currentTicket() }, 'keys_unavailable');
});

test('single-flight startup/verification; issuer and transport origins do not share trust', async () => {
  let calls = 0; let release;
  const pending = new Promise((resolve) => { release = resolve; });
  const input = remote({ fetch: async () => { calls++; await pending; return response(); } });
  const gate = createDeliveryGate(input);
  const promises = [gate.ready(), gate.ready(), ...Array.from({ length: 8 }, () => verify(input))];
  release(); await Promise.all(promises); assert.equal(calls, 1);
  await verify({ ...input, issuer: 'https://issuer.example', ticket: ticket({}, { iss: 'https://issuer.example' }) });
  assert.equal(calls, 2);
  await verify({ ...input, origin: 'https://other-key-source.example' }); assert.equal(calls, 3);
});

test('unknown-kid refetch is single-flight, limited to once per 60s, and recovers staged rotation', async () => {
  let calls = 0; let now = 1700000000000; let publishNew = false;
  const input = remote({ now: () => now, fetch: async () => { calls++; await Promise.resolve(); return response(publishNew ? [fixture.publicJwk, alternate.jwk] : undefined); } });
  await verify(input); assert.equal(calls, 1);
  const unknown = () => ({ ...input, ticket: ticket({}, { iat: now / 1000, exp: now / 1000 + 60 }, alternate) });
  await Promise.all(Array.from({ length: 8 }, () => rejects(unknown(), 'unknown_key')));
  assert.equal(calls, 2);
  await rejects({ ...input, ticket: ticket({ kid: 'A'.repeat(43) }) }, 'unknown_key'); assert.equal(calls, 2);
  now += 59000; publishNew = true;
  await rejects(unknown(), 'unknown_key'); assert.equal(calls, 2);
  now += 1000; await verify(unknown()); assert.equal(calls, 3);
  await verify(unknown()); assert.equal(calls, 3);
});

test('failed unknown-kid refresh preserves fresh known keys; malformed sets never replace cache', async () => {
  let calls = 0; let now = 1700000000000; let bad = false;
  const input = remote({ now: () => now, fetch: async () => { calls++; return bad ? response([fixture.publicJwk, {}]) : response(); } });
  await verify(input); bad = true;
  await rejects({ ...input, ticket: ticket({}, {}, alternate) }, 'keys_unavailable');
  await verify(input); assert.equal(calls, 2);
  await rejects({ ...input, ticket: ticket({}, {}, alternate) }, 'unknown_key'); assert.equal(calls, 2);
  now += 300000;
  await rejects({ ...input, ticket: ticket({}, { iat: now / 1000, exp: now / 1000 + 60 }) }, 'keys_unavailable');
  bad = false;
  await verify({ ...input, ticket: ticket({}, { iat: now / 1000, exp: now / 1000 + 60 }) });
});

test('request extraction: query, bearer, both, duplicates, none, malformed and combined auth', async () => {
  const request = (query = '', auth) => new Request('https://files.example/' + query, { headers: auth === undefined ? {} : { authorization: auth } });
  assert.equal(ticketFromRequest(request('?ticket=' + fixture.ticket)), fixture.ticket);
  assert.equal(ticketFromRequest(request('?%74icket=' + fixture.ticket)), fixture.ticket);
  assert.equal(ticketFromRequest(request('', 'Bearer ' + fixture.ticket)), fixture.ticket);
  assert.equal(ticketFromRequest(request('', 'bearer ' + fixture.ticket)), fixture.ticket);
  assert.equal(ticketFromRequest(request()), null);
  assert.equal(ticketFromRequest(request('', 'Bearer opaque-token')), 'opaque-token');
  for (const req of [request('?ticket=a&ticket=b'), request('?ticket=a&%74icket=a'), request('?ticket='),
    request('?ticket=' + fixture.ticket, 'Bearer ' + fixture.ticket), request('?ticket=a', 'Basic aaa'),
    request('', 'Bearer'), request('', 'Basic aaa'), request('', 'Bearer  ' + fixture.ticket),
    request('', 'Bearer ' + fixture.ticket + ', Bearer ' + fixture.ticket)]) {
    assert.throws(() => ticketFromRequest(req), { code: 'invalid_ticket' });
  }
  const gate = createDeliveryGate(base); await gate.ready();
  assert.deepEqual(await gate.verify(fixture.ticket), await gate.verifyRequest(request('?ticket=' + fixture.ticket)));
  await assert.rejects(gate.verifyRequest(request()), { code: 'invalid_ticket' });
  const { verifyRequest } = gate;
  await verifyRequest(request('', 'Bearer ' + fixture.ticket));
});

test('replay store consumes only verified tickets; false, exceptions and invalid results deny', async () => {
  let calls = 0;
  const replayStore = { async consume(jti, exp) { calls++; assert.equal(jti, fixture.claims.jti); assert.equal(exp, fixture.claims.exp); return true; } };
  await verify({ ...base, replayStore }); assert.equal(calls, 1);
  await rejects({ ...base, replayStore, ticket: fixture.negative[1].ticket }); assert.equal(calls, 1);
  await rejects({ ...base, replayStore, now: () => fixture.claims.exp * 1000 }, 'ticket_expired'); assert.equal(calls, 1);
  await rejects({ ...base, replayStore: { async consume() { return false; } } }, 'replay');
  await rejects({ ...base, replayStore: { async consume() { throw new Error('sensitive backend'); } } }, 'replay_store_error');
  for (const result of [undefined, null, 1, 'true']) await rejects({ ...base, replayStore: { async consume() { return result; } } }, 'replay_store_error');
  await rejects({ ...base, replayStore: {} }, 'replay_store_error');
});

test('concurrent replay with fake atomic store admits exactly one', async () => {
  const seen = new Set();
  const replayStore = { async consume(jti) { if (seen.has(jti)) return false; seen.add(jti); await Promise.resolve(); return true; } };
  const results = await Promise.allSettled(Array.from({ length: 12 }, () => verify({ ...base, replayStore })));
  assert.equal(results.filter((r) => r.status === 'fulfilled').length, 1);
  for (const result of results.filter((r) => r.status === 'rejected')) assert.equal(result.reason.code, 'replay');
});

test('unsupported_crypto explicitly denies missing subtle and missing standard Ed25519 without downgrading', async (t) => {
  const descriptor = Object.getOwnPropertyDescriptor(globalThis, 'crypto');
  t.after(() => Object.defineProperty(globalThis, 'crypto', descriptor));
  for (const crypto of [undefined, {}, { subtle: {} }, { subtle: {
    digest: webcrypto.subtle.digest.bind(webcrypto.subtle),
    async importKey(format, key, algorithm) { assert.equal(algorithm.name, 'Ed25519'); throw new DOMException('unsupported', 'NotSupportedError'); },
    async verify() { throw new Error('must not downgrade'); },
  } }, { subtle: {
    digest: webcrypto.subtle.digest.bind(webcrypto.subtle), importKey: webcrypto.subtle.importKey.bind(webcrypto.subtle),
    async verify(algorithm) { assert.equal(algorithm, 'Ed25519'); throw new DOMException('unsupported', 'NotSupportedError'); },
  } }]) {
    Object.defineProperty(globalThis, 'crypto', { value: crypto, configurable: true });
    await rejects(base, 'unsupported_crypto');
    await assert.rejects(createDeliveryGate(base).ready(), { code: 'unsupported_crypto' });
  }
});

test('the default fetch is called with globalThis as `this` (Cloudflare Workers reject a detached fetch)', async () => {
  const original = globalThis.fetch;
  // Real Workers throw "Illegal invocation" here; Node does not, so simulate it.
  globalThis.fetch = function fetchStub() { if (this !== globalThis) throw new TypeError('Illegal invocation'); return response(); };
  try {
    const result = await verify(remote({ fetch: undefined }));
    assert.equal(result.product, fixture.claims.product);
  } finally { globalThis.fetch = original; }
});
