import type {
  DirectoryEntry,
  DirectorySourceType,
} from '@/lib/directory/types';

const VERIFIED_AT = '2026-07-13';

// 週次運用 (JPYC Service Monitor) では、再検証したエントリだけ verifiedAt を、事実を書き換えた
// エントリだけ updatedAt を per-entry で進める。更新時は lib/directory/serviceMonitor.ts の
// MANUAL_CHANGELOG に同一 PR でイベントを追記すること (運用 runbook: plans/jpyc-service-monitor.md)。
function provenance(
  sourceUrl: string,
  attribution: string,
  sourceType: DirectorySourceType = 'official',
  dates: { verifiedAt?: string; updatedAt?: string } = {},
) {
  return {
    sourceUrl,
    sourceType,
    verifiedAt: dates.verifiedAt ?? VERIFIED_AT,
    updatedAt: dates.updatedAt ?? VERIFIED_AT,
    attribution,
  } as const;
}

/**
 * 公開データは一次ソースで確認できた事実だけを保持する。不明な capability は false / []。
 * editorial は OpenPay が本ディレクトリ向けに独自作成した文で、一次ソース本文を転載しない。
 */
export const DIRECTORY_ENTRIES = [
  {
    slug: 'jpyc-ex',
    name: 'JPYC EX',
    nameJa: 'JPYC EX',
    status: 'published',
    ...provenance('https://jpyc.co.jp/', 'JPYC株式会社'),
    facts: {
      description: 'JPYCの発行と償還を受け付ける公式プラットフォーム。',
      category: 'exchange',
      tags: ['Japan', 'issuance', 'redemption'],
      tokens: ['jpyc'],
      chains: ['avalanche', 'ethereum', 'polygon'],
      languages: ['ja'],
      supportsJpyc: true,
      supportsUsdc: false,
      supportsX402: false,
      supportsMcp: false,
    },
    editorial: {
      summaryJa: 'JPYCの発行・償還手続きを始める際の公式窓口です。',
      summaryEn: 'The official starting point for JPYC issuance and redemption.',
    },
  },
  {
    slug: 'sbi-vc-trade',
    name: 'SBI VC Trade',
    nameJa: 'SBI VCトレード',
    status: 'published',
    ...provenance('https://www.sbivc.co.jp/', 'SBI VCトレード株式会社'),
    facts: {
      description: '日本円建ての取引を提供し、USDCを取り扱う国内暗号資産交換業者。',
      category: 'exchange',
      tags: ['Japan', 'JPY', 'exchange'],
      tokens: ['usdc'],
      chains: [],
      languages: ['ja'],
      supportsJpyc: false,
      supportsUsdc: true,
      supportsX402: false,
      supportsMcp: false,
    },
    editorial: {
      summaryJa: '国内でUSDCと日本円の取引先を調べる際の候補です。',
      summaryEn: 'A Japan-based option for users researching USDC and JPY trading.',
    },
  },
  {
    slug: 'bitbank',
    name: 'bitbank',
    nameJa: 'ビットバンク',
    status: 'published',
    ...provenance('https://bitbank.cc/', 'ビットバンク株式会社'),
    facts: {
      description: '日本円建ての暗号資産取引を提供する国内暗号資産交換業者。',
      category: 'exchange',
      tags: ['Japan', 'JPY', 'exchange'],
      tokens: [],
      chains: [],
      languages: ['ja'],
      supportsJpyc: false,
      supportsUsdc: false,
      supportsX402: false,
      supportsMcp: false,
    },
    editorial: {
      summaryJa: '国内取引所を比較するときに確認できる公式情報源の一つです。',
      summaryEn: 'One official source to consult when comparing Japanese exchanges.',
    },
  },
  {
    slug: 'coincheck',
    name: 'Coincheck',
    nameJa: 'コインチェック',
    status: 'published',
    ...provenance('https://coincheck.com/', 'コインチェック株式会社'),
    facts: {
      description: '日本国内で暗号資産の売買サービスを提供する暗号資産交換業者。',
      category: 'exchange',
      tags: ['Japan', 'JPY', 'exchange'],
      tokens: [],
      chains: [],
      languages: ['ja'],
      supportsJpyc: false,
      supportsUsdc: false,
      supportsX402: false,
      supportsMcp: false,
    },
    editorial: {
      summaryJa: '国内の暗号資産売買サービスを調べるための公式サイトです。',
      summaryEn: 'An official site for researching a Japan-based crypto trading service.',
    },
  },
  {
    slug: 'usdc-bridge',
    name: 'USDC Bridge',
    nameJa: 'USDC Bridge',
    status: 'published',
    ...provenance('https://bridge.usdc.com/', 'Circle Internet Group, Inc.'),
    facts: {
      description: 'Circleが提供するUSDCのクロスチェーン移動用Webアプリケーション。',
      category: 'bridge',
      tags: ['Circle', 'cross-chain', 'bridge'],
      tokens: ['usdc'],
      chains: [],
      languages: ['en'],
      supportsJpyc: false,
      supportsUsdc: true,
      supportsX402: false,
      supportsMcp: false,
    },
    editorial: {
      summaryJa: 'USDCを別チェーンへ移す手段を確認できるCircleの公式画面です。',
      summaryEn: 'Circle\'s official interface for reviewing cross-chain USDC transfers.',
    },
  },
  {
    slug: 'openpay',
    name: 'OpenPay',
    nameJa: 'OpenPay',
    status: 'published',
    ...provenance('https://open-pay.jp/', 'OpenPay'),
    facts: {
      description: 'JPYCとUSDCの受け取り導線およびx402 APIを提供するオープンソースサービス。',
      category: 'payment',
      tags: ['Japan', 'checkout', 'x402'],
      tokens: ['jpyc', 'usdc'],
      chains: [
        'arbitrum',
        'avalanche',
        'base',
        'ethereum',
        'kaia',
        'optimism',
        'polygon',
      ],
      languages: ['en', 'ja'],
      supportsJpyc: true,
      supportsUsdc: true,
      supportsX402: true,
      supportsMcp: false,
    },
    editorial: {
      summaryJa: 'ステーブルコインの受け取りとAPI課金を試せる本ディレクトリの運営サービスです。',
      summaryEn: 'The directory operator\'s service for stablecoin checkout and paid APIs.',
    },
  },
  {
    slug: 'jpyc',
    name: 'JPYC',
    nameJa: 'JPYC',
    status: 'published',
    ...provenance(
      'https://corporate.jpyc.co.jp/news/posts/jpyc-ex-launch',
      'JPYC株式会社',
    ),
    facts: {
      description: '日本円と連動するよう設計された電子決済手段のステーブルコイン。',
      category: 'stablecoin',
      tags: ['Japan', 'JPY', 'stablecoin'],
      tokens: ['jpyc'],
      chains: ['avalanche', 'ethereum', 'polygon'],
      languages: ['ja'],
      supportsJpyc: true,
      supportsUsdc: false,
      supportsX402: false,
      supportsMcp: false,
    },
    editorial: {
      summaryJa: '日本円建てのオンチェーン決済手段を調べる際の基礎情報です。',
      summaryEn: 'A primary reference when researching a JPY-denominated onchain payment asset.',
    },
  },
  {
    slug: 'circle',
    name: 'Circle',
    nameJa: 'Circle',
    status: 'published',
    ...provenance('https://www.circle.com/usdc', 'Circle Internet Group, Inc.'),
    facts: {
      description: 'USDCに関する公式情報と開発者向けサービスを提供する発行者。',
      category: 'stablecoin',
      tags: ['issuer', 'stablecoin', 'developer'],
      tokens: ['usdc'],
      chains: [],
      languages: ['en'],
      supportsJpyc: false,
      supportsUsdc: true,
      supportsX402: false,
      supportsMcp: false,
    },
    editorial: {
      summaryJa: 'USDCの仕様や提供サービスを一次情報で確認するための公式サイトです。',
      summaryEn: 'The official source for checking USDC information and Circle services.',
    },
  },
  {
    slug: 'base',
    name: 'Base',
    nameJa: 'Base',
    status: 'published',
    ...provenance('https://www.base.org/', 'Base'),
    facts: {
      description: 'Coinbaseが構築するEthereum互換のブロックチェーンネットワーク。',
      category: 'network',
      tags: ['EVM', 'L2', 'Coinbase'],
      tokens: ['usdc'],
      chains: ['base'],
      languages: ['en'],
      supportsJpyc: false,
      supportsUsdc: true,
      supportsX402: true,
      supportsMcp: false,
    },
    editorial: {
      summaryJa: 'USDC決済やx402の構築先として参照できるEVMネットワークです。',
      summaryEn: 'An EVM network to consider for USDC payments and x402 applications.',
    },
  },
  {
    slug: 'polygon',
    name: 'Polygon',
    nameJa: 'Polygon',
    status: 'published',
    ...provenance('https://polygon.technology/', 'Polygon Labs'),
    facts: {
      description: 'Ethereum互換のアプリケーションと決済に利用されるブロックチェーンネットワーク。',
      category: 'network',
      tags: ['EVM', 'payments', 'network'],
      tokens: [],
      chains: ['polygon'],
      languages: ['en'],
      supportsJpyc: false,
      supportsUsdc: false,
      supportsX402: false,
      supportsMcp: false,
    },
    editorial: {
      summaryJa: 'EVM上の決済アプリケーションを調べる際のネットワーク情報源です。',
      summaryEn: 'A network reference for researching EVM-based payment applications.',
    },
  },
  {
    slug: 'kaia',
    name: 'Kaia',
    nameJa: 'Kaia',
    status: 'published',
    ...provenance('https://www.kaia.io/ja/about', 'Kaia DLT Foundation'),
    facts: {
      description: 'アジア圏のステーブルコイン利用を対象に含むEVM互換レイヤー1ネットワーク。',
      category: 'network',
      tags: ['Asia', 'EVM', 'L1'],
      tokens: ['jpyc'],
      chains: ['kaia'],
      languages: ['en', 'ja'],
      supportsJpyc: true,
      supportsUsdc: false,
      supportsX402: false,
      supportsMcp: false,
    },
    editorial: {
      summaryJa: 'アジア向けのEVMネットワークとステーブルコイン動向を追うための入口です。',
      summaryEn: 'A starting point for following an Asia-focused EVM and its stablecoin ecosystem.',
    },
  },
  {
    slug: 'circle-cctp',
    name: 'Circle CCTP',
    nameJa: 'Circle CCTP',
    status: 'published',
    ...provenance(
      'https://www.circle.com/cross-chain-transfer-protocol',
      'Circle Internet Group, Inc.',
    ),
    facts: {
      description: 'USDCを対応チェーン間で移動させるためのCircle公式プロトコル。',
      category: 'bridge',
      tags: ['Circle', 'cross-chain', 'protocol'],
      tokens: ['usdc'],
      chains: [],
      languages: ['en'],
      supportsJpyc: false,
      supportsUsdc: true,
      supportsX402: false,
      supportsMcp: false,
    },
    editorial: {
      summaryJa: 'USDCのチェーン間移動を実装する開発者向けの一次情報です。',
      summaryEn: 'A primary developer reference for implementing cross-chain USDC movement.',
    },
  },
  {
    slug: 'metamask',
    name: 'MetaMask',
    nameJa: 'MetaMask',
    status: 'published',
    ...provenance(
      'https://support.metamask.io/manage-crypto/tokens/how-to-display-tokens-in-metamask/',
      'MetaMask',
    ),
    facts: {
      description: 'EVMネットワーク上のERC-20トークンを追加・表示できるセルフカストディウォレット。',
      category: 'wallet',
      tags: ['self-custody', 'EVM', 'ERC-20'],
      tokens: ['jpyc', 'usdc'],
      chains: ['avalanche', 'base', 'ethereum', 'polygon'],
      languages: ['en'],
      supportsJpyc: true,
      supportsUsdc: true,
      supportsX402: false,
      supportsMcp: false,
    },
    editorial: {
      summaryJa: '対応ネットワーク上のJPYCやUSDCを管理するウォレット候補です。',
      summaryEn: 'A wallet option for managing JPYC or USDC on compatible networks.',
    },
  },
  {
    slug: 'rabby-wallet',
    name: 'Rabby Wallet',
    nameJa: 'Rabby Wallet',
    status: 'published',
    ...provenance('https://rabby.io/', 'DeBank Global'),
    facts: {
      description: 'EVMエコシステム向けのセルフカストディウォレット。',
      category: 'wallet',
      tags: ['self-custody', 'EVM', 'ERC-20'],
      tokens: ['jpyc', 'usdc'],
      chains: [],
      languages: ['en'],
      supportsJpyc: true,
      supportsUsdc: true,
      supportsX402: false,
      supportsMcp: false,
    },
    editorial: {
      summaryJa: 'EVM上のJPYCやUSDCを扱う際に比較できるウォレットです。',
      summaryEn: 'A wallet to compare when working with JPYC or USDC on EVM networks.',
    },
  },
  {
    slug: 'coinbase-wallet',
    name: 'Coinbase Wallet',
    nameJa: 'Coinbase Wallet',
    status: 'published',
    ...provenance(
      'https://help.coinbase.com/wallet/getting-started/what-types-of-crypto-does-wallet-support',
      'Coinbase, Inc.',
    ),
    facts: {
      description: 'ERC-20トークンと複数のEVM互換ネットワークに対応するセルフカストディウォレット。',
      category: 'wallet',
      tags: ['self-custody', 'EVM', 'ERC-20'],
      tokens: ['jpyc', 'usdc'],
      chains: [
        'arbitrum',
        'avalanche',
        'base',
        'ethereum',
        'optimism',
        'polygon',
      ],
      languages: ['en'],
      supportsJpyc: true,
      supportsUsdc: true,
      supportsX402: false,
      supportsMcp: false,
    },
    editorial: {
      summaryJa: '複数EVMネットワークでトークンを管理するためのウォレット候補です。',
      summaryEn: 'A wallet option for token management across several EVM networks.',
    },
  },
  {
    slug: 'aegis-ai',
    name: 'Aegis',
    nameJa: 'Aegis',
    status: 'published',
    ...provenance('https://aegis-ai.xyz/', 'Aegis'),
    facts: {
      description: 'x402対応を掲げるAIエージェント向けサービス。',
      category: 'api',
      tags: ['AI agent', 'x402', 'API'],
      tokens: [],
      chains: [],
      languages: ['en'],
      supportsJpyc: false,
      supportsUsdc: false,
      supportsX402: true,
      supportsMcp: false,
    },
    editorial: {
      summaryJa: 'x402対応サービスを探す開発者が確認できるAI関連プロジェクトです。',
      summaryEn: 'An AI project for developers surveying x402-enabled services.',
    },
  },
  {
    slug: 'openpay-x402-demo-api',
    name: 'OpenPay x402 Demo API',
    nameJa: 'OpenPay x402デモAPI',
    status: 'published',
    ...provenance('https://open-pay.jp/api/paid/demo', 'OpenPay'),
    facts: {
      description: 'JPYC支払い後にJSONを返すOpenPay運営のx402デモAPI。',
      category: 'api',
      tags: ['first-party', 'x402', 'paid API'],
      tokens: ['jpyc'],
      chains: ['polygon'],
      languages: ['en'],
      supportsJpyc: true,
      supportsUsdc: false,
      supportsX402: true,
      supportsMcp: false,
    },
    editorial: {
      summaryJa: 'JPYC建てx402のchallengeから解錠までを小さく試せるAPIです。',
      summaryEn: 'A compact API for trying a JPYC x402 challenge and unlock flow.',
    },
  },
  {
    slug: 'openpay-stores-api',
    name: 'OpenPay Stores API',
    nameJa: 'OpenPay店舗データAPI',
    status: 'published',
    ...provenance('https://open-pay.jp/api/paid/stores', 'OpenPay'),
    facts: {
      description: 'JPYC支払い後に審査済みサービス一覧を返すOpenPay運営のx402 API。',
      category: 'api',
      tags: ['first-party', 'x402', 'data API'],
      tokens: ['jpyc'],
      chains: ['polygon'],
      languages: [],
      supportsJpyc: true,
      supportsUsdc: false,
      supportsX402: true,
      supportsMcp: false,
    },
    editorial: {
      summaryJa: '有料JSONデータ取得のx402連携を確認するためのfirst-party APIです。',
      summaryEn: 'A first-party API for testing x402 access to paid JSON data.',
    },
  },
  {
    slug: 'openpay-x402-mcp',
    name: 'openpay-x402-mcp',
    nameJa: 'openpay-x402-mcp',
    status: 'published',
    ...provenance(
      'https://www.npmjs.com/package/openpay-x402-mcp',
      'OpenPay',
    ),
    facts: {
      description: 'MCPクライアントからx402リソースの探索と支払いを扱うnpmパッケージ。',
      category: 'developer-tool',
      tags: ['MCP', 'npm', 'x402'],
      tokens: ['jpyc'],
      chains: ['polygon'],
      languages: ['en'],
      supportsJpyc: true,
      supportsUsdc: false,
      supportsX402: true,
      supportsMcp: true,
    },
    editorial: {
      summaryJa: 'MCP対応エージェントからx402リソースを利用するための接続ツールです。',
      summaryEn: 'A connector for using x402 resources from MCP-capable agents.',
    },
  },
  {
    slug: 'directory-draft-fixture',
    name: 'Directory Draft Fixture',
    nameJa: '',
    status: 'draft',
    ...provenance('https://open-pay.jp/', 'OpenPay', 'manual'),
    facts: {
      description: '非公開フェンスの検証だけに使う手動登録のダミー。',
      category: 'developer-tool',
      tags: [],
      tokens: [],
      chains: [],
      languages: [],
      supportsJpyc: false,
      supportsUsdc: false,
      supportsX402: false,
      supportsMcp: false,
    },
    editorial: {
      summaryJa: '公開APIには出さないテスト用エントリです。',
      summaryEn: 'A test-only entry that must never reach public APIs.',
    },
  },
] as const satisfies readonly DirectoryEntry[];
